version: '3.8'
services:
  ums:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=mysqlserver
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=ums
      - MYSQL_PASSWORD=ums
      - MYSQL_DATABASE=ums
    volumes:
      - mysql_data:/home/naim/var/lib/mysql
      - mysql_config:/home/naim/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: