services:
  ums:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DB_URI=mongodb://ums:ums@mongoserver:27017
      - DB_NAME=ums
    volumes:
      - ./:/app
      - ${MAVEN_LOCAL_REPO:-/root/.m2}:/root/.m2
    depends_on:
      - mongoserver
    networks:
      - ums-net
    container_name: ums

  mongoserver:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ums
      - MONGO_INITDB_ROOT_PASSWORD=ums
      - MONGO_INITDB_DATABASE=ums
    volumes:
      - mongodb_data:/data/db
    networks:
      - ums-net

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ums
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ums
      - ME_CONFIG_MONGODB_URL=mongodb://ums:ums@mongoserver:27017/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongoserver
    networks:
      - ums-net

networks:
  ums-net:
    driver: bridge

volumes:
  mongodb_data:
